# Generated by Django 3.0.5 on 2020-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfriend',
            name='status',
            field=models.TextField(default='A'),
        ),
    ]
