# Generated by Django 3.0.5 on 2020-06-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200531_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_msg', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.UserFriend')),
            ],
        ),
    ]
